const FETCH_ESTACIONES_LIST = 'FETCH_ESTACIONES_LIST';
const FETCH_ESTACIONES_ERROR = 'FETCH_ESTACIONES_ERROR';
const FETCH_ESTACIONES_SUCCESS = 'FETCH_ESTACIONES_SUCCESS';

export { FETCH_ESTACIONES_LIST, FETCH_ESTACIONES_ERROR, FETCH_ESTACIONES_SUCCESS };
