const FETCH_ESTACIONES_LIST = 'FETCH_ESTACIONES_LIST';
const FETCH_ESTACIONES_ERROR = 'FETCH_ESTACIONES_ERROR';
const FETCH_ESTACIONES_SUCCESS = 'FETCH_ESTACIONES_SUCCESS';
const ESTACIONES_BUTTON_CLICK = 'ESTACIONES_BUTTON_CLICK';
const ESTACION_CLICK = 'ESTACION_CLICK';
const HIDE_ERRORS = 'HIDE_ERRORS';
const SHOW_ERRORS = 'SHOW_ERRORS';
const SECTOR_CLICK = 'SECTOR_CLICK';

export { 
  FETCH_ESTACIONES_LIST, 
  FETCH_ESTACIONES_ERROR, 
  FETCH_ESTACIONES_SUCCESS, 
  ESTACIONES_BUTTON_CLICK,
  ESTACION_CLICK,
  HIDE_ERRORS,
  SHOW_ERRORS,
  SECTOR_CLICK
};
