const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const FETCH_MARVEL_LIST = 'FETCH_MARVEL_LIST';
const FETCH_MARVEL_SUCCESS = 'FETCH_MARVEL_SUCCESS';
const FETCH_MARVEL_ERROR = 'FETCH_MARVEL_ERROR';


export { CHANGE_LANGUAGE, FETCH_MARVEL_LIST, FETCH_MARVEL_ERROR, FETCH_MARVEL_SUCCESS };
