const SELECT_BUSCADOR_BICI_SKI = 'SELECT_BUSCADOR_BICI_SKI';
const FETCHING_USER_INFO = 'FETCHING_USER_INFO';
const FETCH_USER_INFO_ERROR = 'FETCH_USER_INFO_ERROR';
const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export {
  SELECT_BUSCADOR_BICI_SKI,
  FETCHING_USER_INFO,
  FETCH_USER_INFO_ERROR,
  FETCH_USER_INFO_SUCCESS
}