const FETCH_ESTACIONES_LIST_BICI = 'FETCH_ESTACIONES_LIST_BICI';
const FETCH_ESTACIONES_ERROR_BICI = 'FETCH_ESTACIONES_ERROR_BICI';
const FETCH_ESTACIONES_SUCCESS_BICI = 'FETCH_ESTACIONES_SUCCESS_BICI';
const ESTACIONES_BUTTON_CLICK_BICI = 'ESTACIONES_BUTTON_CLICK_BICI';
const ESTACION_CLICK_BICI = 'ESTACION_CLICK_BICI';
const HIDE_ERRORS_BICI = 'HIDE_ERRORS_BICI';
const SHOW_ERRORS_BICI = 'SHOW_ERRORS_BICI';
const SECTOR_CLICK_BICI = 'SECTOR_CLICK_BICI';
const START_DATE_SELECTION_BICI = 'START_DATE_SELECTION_BICI';
const END_DATE_SELECTION_BICI = 'END_DATE_SELECTION_BICI';
const SKY_SUBMIT_CLICK_BICI = 'SKY_SUBMIT_CLICK_BICI';
const FORFAIT_BUTTON_CLICK_BICI = 'FORFAIT_BUTTON_CLICK_BICI';
const CUANTOS_DIAS_SELECTION = 'CUANTOS_DIAS_SELECTION';

export {  
  FETCH_ESTACIONES_LIST_BICI, 
  FETCH_ESTACIONES_ERROR_BICI, 
  FETCH_ESTACIONES_SUCCESS_BICI, 
  ESTACIONES_BUTTON_CLICK_BICI,
  ESTACION_CLICK_BICI,
  HIDE_ERRORS_BICI,
  SHOW_ERRORS_BICI,
  SECTOR_CLICK_BICI,
  START_DATE_SELECTION_BICI,
  END_DATE_SELECTION_BICI,
  SKY_SUBMIT_CLICK_BICI,
  FORFAIT_BUTTON_CLICK_BICI,
  CUANTOS_DIAS_SELECTION
};
